leg1:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  position_only_ik: True
  #cartesian_path:
  #  jump_threshold: 0.15
  #  revolute_jump_threshold: 1.5
  #  prismatic_jump_threshold: 0.0
