# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - legs_controller

  legs_controller:
    type: FollowJointTrajectory
    joints:
      - servo1_servo1_padding
      - servo2_servo2_padding
      - servo3_calfJoint
    action_ns: follow_joint_trajectory
    default: true
