# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    leg_FR_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    leg_FL_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    leg_BR_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    leg_BL_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

leg_FR_controller:
  ros__parameters:
    joints:
      - servo1_servo1_padding_FR
      - servo2_servo2_padding_FR
      - servo3_calfFeet_FR
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true
leg_FL_controller:
  ros__parameters:
    joints:
      - servo1_servo1_padding_FL
      - servo2_servo2_padding_FL
      - servo3_calfFeet_FL
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true
leg_BR_controller:
  ros__parameters:
    joints:
      - servo1_servo1_padding_BR
      - servo2_servo2_padding_BR
      - servo3_calfFeet_BR
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true
leg_BL_controller:
  ros__parameters:
    joints:
      - servo1_servo1_padding_BL
      - servo2_servo2_padding_BL
      - servo3_calfFeet_BL
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true