# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    leg1_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      update_rate: 100  # Hz

leg1_controller:
  ros__parameters:
    joints:
      - servo1_servo1_padding
      - servo2_servo2_padding
      - servo3_calfFeet
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true
